FORMAT: 1A
HOST: http://jobnow.apiblueprint.org/

# JobNow

This api can be used for the development of mobile and web version of JobNow service.

# Group Authorization

## Login [/auth/login]

### Get an Access Token [POST]

You must provide the Authorization: {access_token} header in all other requests.

+ Request (application/json)

        {
            "username": "+375291234567",
            "password": "password"
        }

+ Response 200 (application/json)

    + Body

            {
                "token": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiY3JlYXRlZCI6MTQ3OTM4NTQ2OTkyMSwiZXhwIjoxNDgyMTA3MDY5fQ.1OurxLH4nCzvt5K4uhcv_dbs4QX0pIHb3-cm6zJiLSilclUSd_vSKfBY5TrQSSmhrTFVs5r9SWeVwH5sJenAJQ",
            }

+ Response 401 (application/json)

    + Body

            {
                "message": "Wrong username or password"
            }
 
# Group Account

## Account and Registration [/account]

### Create an Account [POST]

You need to get confirmation code from the request "Phone Confirmation".

+ Request (application/json)

        {
            "phone": "+375291234567",
            "confirmation_code": "123456",
            "given_name": "Ivan",
            "family_name": "Ivanov",
            "email": "ivanov@mail.com",
            "communication_method": 0,
            "basic_info": "Some information about user",
            "image_data": "{image_data}"
        }

+ Response 201 (application/json)

    + Body

            {
                "message": "OK"
            }

+ Response 401 (application/json)

    + Body

            {
                "message": "Wrong phone number/ confirmation code / empty family or given name."
            }

### Get an Accounts Information [GET]

+ Request
    + Headers
            
            Authorization: {access_token}

+ Response 200 (application/json)

    + Body

            {
                "given_name": "Ivan",
                "family_name": "Ivanov",
                "phone": "+375291234567",
                "email": "ivanov@mail.com",
                "communication_method": 0,
                "basic_info": "Some information about user",
                "image_url": "{link_to_s3}"
            }
            
### Change an Account [PUT]
+ Request (application/json)
    + Headers
            
            Authorization: {access_token}

    + Body
    
            {
                "given_name": "Ivan",
                "family_name": "Ivanov",
                "email": "ivanov@mail.com",
                "communication_method": 0,
                "basic_info": "Some information about user",
                "image_data": "{image_data}"
            }

+ Response 201 (application/json)

    + Body

            {
                "message": "OK"
            }

+ Response 401 (application/json)

    + Body

            {
                "message": "Empty family or given name..."
            }

### Delete an Account [DELETE]

+ Request 
    + Headers
            
            Authorization: {access_token}

+ Response 201 (application/json)

    + Body

            {
                "message": "OK"
            }


## Phone Confirmation [/account/phone_confirmation]

### Send SMS [POST]

Use this request for sending SMS with confirmation code for regitration.

+ Request (application/json)

        {
            "phone": "+375291234567"
        }

+ Response 201 (application/json)

    + Body

            {
                "message": "OK"
            }

+ Response 401 (application/json)

    + Body

            {
                "message": "Wrong phone number"
            }