# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'JobNow' do
  pod 'Firebase/Messaging'
end

target 'JobNowTests' do

end

target 'JobNow-tvOS' do

end

target 'JobNow-tvOSTests' do

end
